"""empty message

Revision ID: 2e326859cc30
Revises: b39060bdf746
Create Date: 2019-01-13 03:42:58.345359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e326859cc30'
down_revision = 'b39060bdf746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('res_docclasses',
    sa.Column('docclass_id', sa.Integer(), nullable=False),
    sa.Column('docclass_pid', sa.Integer(), nullable=True),
    sa.Column('docclass_name', sa.String(length=128), nullable=True),
    sa.Column('docclass_createtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docclass_pid'], ['res_docclasses.docclass_id'], ),
    sa.PrimaryKeyConstraint('docclass_id')
    )
    op.create_table('res_docs',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('doc_title', sa.String(length=64), nullable=True),
    sa.Column('doc_summary', sa.String(length=512), nullable=True),
    sa.Column('doc_content_html', sa.Text(), nullable=True),
    sa.Column('doc_sort', sa.Integer(), nullable=True),
    sa.Column('doc_isshow', sa.Boolean(), nullable=True),
    sa.Column('doc_updatetime', sa.DateTime(), nullable=True),
    sa.Column('doc_createtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['ua_users.ua_user_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['res_docclasses.docclass_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('res_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('file_uri', sa.String(length=512), nullable=True),
    sa.Column('file_isextern', sa.Boolean(), nullable=True),
    sa.Column('file_createtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['ua_users.ua_user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('res_files')
    op.drop_table('res_docs')
    op.drop_table('res_docclasses')
    # ### end Alembic commands ###
