"""empty message

Revision ID: b39060bdf746
Revises: 
Create Date: 2019-01-12 18:59:12.908387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39060bdf746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ua_users',
    sa.Column('ua_user_id', sa.Integer(), nullable=False),
    sa.Column('ua_user_name', sa.String(length=64), nullable=True),
    sa.Column('ua_user_email', sa.String(length=128), nullable=True),
    sa.Column('ua_user_nick', sa.String(length=64), nullable=True),
    sa.Column('ua_pwd_hash', sa.String(length=128), nullable=True),
    sa.Column('ua_createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ua_user_id')
    )
    op.create_index(op.f('ix_ua_users_ua_user_email'), 'ua_users', ['ua_user_email'], unique=True)
    op.create_index(op.f('ix_ua_users_ua_user_name'), 'ua_users', ['ua_user_name'], unique=True)
    op.create_index(op.f('ix_ua_users_ua_user_nick'), 'ua_users', ['ua_user_nick'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ua_users_ua_user_nick'), table_name='ua_users')
    op.drop_index(op.f('ix_ua_users_ua_user_name'), table_name='ua_users')
    op.drop_index(op.f('ix_ua_users_ua_user_email'), table_name='ua_users')
    op.drop_table('ua_users')
    # ### end Alembic commands ###
